Collections
lbryio/lbry-redux pull request #383
Opened 2021-02-15 19:35 UTC by jessopb

2021-02-15 22:12 UTC, seanyesmunt requested changes

2021-02-15 22:12 UTC, seanyesmunt commented on src/redux/actions/claims.js
> +        dispatch(doFetchClaimListMine(1, 10));
doFetchCollectionListMine

2021-02-15 22:12 UTC, seanyesmunt commented on src/redux/reducers/collections.js
> +      id: 'watchlater',
make watchlater a constant

2021-02-15 22:12 UTC, seanyesmunt commented on src/redux/reducers/collections.js
> +      newLists[id]['updatedAt'] = getTimestamp();
move this to the action

2021-02-15 22:12 UTC, seanyesmunt commented on src/redux/reducers/collections.js
> +    [ACTIONS.PLAYLIST_CREATE]: (state, action) => {
COLLECTION_UNPUBLISHED_CREATE

2021-02-15 22:12 UTC, seanyesmunt commented on src/redux/reducers/collections.js
> +        newResolving.push(id);
resolvingCollectionById[id] = true

From comment above about keeping this the same type as isResolvingClaimsById

2021-02-15 22:12 UTC, seanyesmunt commented on src/redux/selectors/claims.js
> +// selectMyCollectionUrls
comment

2021-02-15 22:12 UTC, seanyesmunt commented on src/redux/selectors/collections.js
> +export const selectBuiltinPlaylists = createSelector(
selectBuiltinCollections

2021-02-15 22:12 UTC, seanyesmunt commented on src/redux/selectors/collections.js
> +      return state.isResolvingCollectionById.includes(id);
return state.isResolvingCollectionById[id]

2021-02-17 16:16 UTC, jessopb commented on src/redux/actions/collections.js
> +  const resolvedCollectionItemsById: Array<{ [string]: Array<GenericClaim> }> = await Promise.all(
Array/< { claimId: string, items: ?Array<GenericClaim> } >

2021-06-04 12:28 UTC, infinite-persistence reviewed
First pass ok.  Mostly indirectly tested using the Desktop PR.  
Only minor (ignorable) cleanup here.

2021-06-04 12:28 UTC, infinite-persistence commented on dist/flow-typed/Collections.js
> +  sourceid?: string, // if copied, claimId of original collection
typo?

2021-06-04 12:28 UTC, infinite-persistence commented on src/redux/actions/claims.js
> +  makeSelectEditedCollectionForId,
There are a few unused variables in this file.

2021-06-04 12:28 UTC, infinite-persistence commented on src/redux/actions/collections.js
> +  makeSelectMyPublishedCollectionForId,
Unused

2021-06-08 15:51 UTC, merged