Move `getChannelLevel` to a selector.
lbryio/lbry-redux pull request #387
Opened 2021-03-09 14:12 UTC by infinite-persistence

## Issue
#5636: Disable video previews in comments/posts made by channels below a certain channel staked level

2021-03-09 21:20 UTC, seanyesmunt requested changes

2021-03-09 21:20 UTC, seanyesmunt commented on src/redux/selectors/claims.js
> +        case amount >= 1 && amount < 50:
Can you separate these values into https://github.com/lbryio/lbry-redux/blob/master/src/constants/claim.js

`export const LEVEL_1_STAKED_AMOUNT = 1`
`export const LEVEL_2_STAKED_AMOUNT = 2`
...

2021-03-10 00:24 UTC, infinite-persistence commented
`Update`
- Used constants for the levels

2021-03-11 17:43 UTC, seanyesmunt commented on src/redux/selectors/claims.js
> +        case amount >= 1 && amount < 50:
Whoops. I realized I have a typo in my message. I'll fix it.

2021-03-11 17:57 UTC, seanyesmunt approved these changes

2021-03-11 17:57 UTC, merged